preprocess:
  input: data/raw/diabetes.csv
  output: data/processd/diabetes.csv


train:
   data: data/processd/diabetes.csv
   model: models/model.pkl
   random_state: 42
   n_estimators: 100
   max_depth: 5