preprocess:
  input: data/raw/diabetes.csv
  output: data/processd/diabetes.csv


train:
   data_path: data/processd/diabetes.csv
   local_model_path: models/model.pkl
   random_state: 42
   n_estimators: 100
   max_depth: 5
   mlflow:
    tracking_uri: 
    tracking_username: 
    tracking_password: 
   hyperparamter:
       